aux_source_directory(./ srcDir)
aux_source_directory(./nvic srcDir)
aux_source_directory(./mem srcDir)
aux_source_directory(./dma srcDir)
aux_source_directory(./sdmmc srcDir)
aux_source_directory(./uart srcDir)
aux_source_directory(./gpio srcDir)
aux_source_directory(./spi srcDir)
aux_source_directory(./can srcDir)
aux_source_directory(./i2c srcDir)
aux_source_directory(./usb srcDir)
get_filename_component(LIB_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)

add_library(${LIB_NAME} STATIC ${srcDir})

if(WITH_RTOS)
target_link_libraries(${LIB_NAME} modules utility freertos_kernel)
else()
target_link_libraries(${LIB_NAME} modules utility)
endif()
